### ISSUE TITLE
GD-90: Aborting test run from Visual Studio causes `GdUnitRunner` file to persist

### ISSUE THREAD

**Issue by DrMouseInc** [MikeSchulze/gdUnit4Net#90]
### The used Test Adapter version

1.1.0

### The used Godot version

v4.2.2.stable.mono.official [15073afe3]

### Operating System

Windows 11

### Describe the bug

Running tests any which way I expect that after the run is complete, the GdUnitRunner_{GUID here}.cfg file is deleted. Instead the file remains, clogging up the project folder and git changes

### Steps to Reproduce

Run tests from Visual Studio using the "Debug Tests" menu option from the right click menu and have a breakpoint set in the test method. Wait for the breakpoint to be hit and the execution halted and then, instead of continuing the run by clicking the Continue with the green arrow, press the "Stop debugging" with the red square.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

**Comment by MikeSchulze** [comment]
close is already fixed with v1.1.1 please update your project

**Comment by DrMouseInc** [comment]
Still seeing this after updating to 1.1.1. I've attached a minimum repro after an aborted test run retained the file
[GdUnitSetup.zip](https://github.com/MikeSchulze/gdUnit4Net/files/15051354/GdUnitSetup.zip)

**Comment by DrMouseInc** [comment]
After the breakpoint is hit, I hit the Stop debugging button. But I get the same outcome by cancelling the tests from the test explorer window.

![image](https://github.com/MikeSchulze/gdUnit4Net/assets/167206053/de702f7a-839a-48d9-ab16-ade79ba11bb6)

If by the logs you mean the Tests dropdown from the Output window of VS, that reads as follows:

> Building Test Projects
> Executing test method: GdUnitSetup.Tests.TestClass1.Test1
> ========== Starting test run ==========
> Start executing tests, 1 TestCases total.
> Current directory set to: C:\Temp\GdUnitSetup
> Run with args -d --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="C:\Temp\GdUnitSetup\GdUnitRunner_58bc84bf-6b5e-4eb4-8ec2-7017411a62cf.cfg" 
> stdout: Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
> stdout: Vulkan API 1.3.262 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6600M
> stdout: Load testsuite C:\Temp\GdUnitSetup\Tests\TestClass1.cs
> The active test run was aborted. Reason: Test host process crashed
> ========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========

**Comment by MikeSchulze** [comment]
Interesting, on Visual Studio Code the logs are different.

```bash
Debugger attached
stdout: Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org
stdout: Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 4070 Ti
stdout: Load testsuite D:\development\workspace\gdUnit4Net\test\src\asserts\BoolAssertTest.cs
stdout: Testrun ends with exit code: 0, FailFast:False
Godot ends with exit code: 0
Run TestRunner ends with 0
========== Test run finished: 9 Tests (9 Passed, 0 Failed, 0 Skipped) run in 8.1 sec ==========
```

looks like the stop do not terminate the process normal, i need to check this inside VS

**Comment by MikeSchulze** [comment]
Looks like a VS Test issue `The active test run was aborted. Reason: Test host process crashed`
https://github.com/microsoft/vstest/issues/2952

So I can't really act on this issue as the test execution process is killed/crashed by the testhost.exe.
I can only add a workaround like, clean up existing runner configuration files before writing the new one.

**Comment by DrMouseInc** [comment]
> So I can't really act on this issue as the test execution process is killed/crashed by the testhost.exe. I can only add a workaround like, clean up existing runner configuration files before writing the new one.

Works for me.

> For now, I suggest adding `**GdUnitRunner_*.cfg` to your `.gitignore`

That'll still leave them on the disk, so I'll rather have them show up in the Git changes tab in VS where from they're easy to delete

**Comment by MikeSchulze** [comment]
> That'll still leave them on the disk, so I'll rather have them show up in the Git changes tab in VS where from they're easy to delete

Yes, sorry, but unfortunately there's nothing I can do.
